### ISSUE TITLE
Add new coordinates tag for initial coordinates 

### ISSUE THREAD

**Issue by valentine195** [valentine195/obsidian-leaflet-plugin#84]
I came across a new use case today: **Auto-centering maps**, ideal if one is on the road a lot.

Some friends and I myself sometimes travel a lot. Now that we are getting Obsidian mobile, or work on a GPS-enabled laptop like myself, it is relatively easy to write a script that automatically updates a note’s YAML with the current (real-world) location. Or just manually enter my current location in my own "Myself" note.

Since Obsidian Leaflet is so amazing getting location and overlay data from notes and auto-updating the maps, I find myself using a two-map note most of the time: One of the maps shows the whole country, the other one **the place I currently stay**, with a radius of approx. 10–25 km.

To make things even more comfortable, it would be just great to have this second "where-I-am" map
- **automatically centered** to the place I currently stay (from a note’s YAML `location:`), and maybe even
- **showing the radius specified in the `nearby:`** YAML of my "Myself" note.

**This would mean getting the `lat:` and `long:` code block entries from another note’s `location:` YAML data**, by somehow specifying the note, i.e. `[[Matthias C. Hormann]]` or `"People/Friends & Family/Matthias C. Hormann"`.

Regarding **the radius (or zoom factor)**, it would also mean reading the specified `overlayTag` (if any) from that note’s YAML, and possibly translating that to a zoom factor (?), defaulting to the `defaultZoom` in the code block.

I already experimented with using inline _Dataview_ (like `=[[Matthias C. Hormann]].location[0]`) and _Templater_ but that of course doesn’t work easily in a code block.

I have no idea if this appeals to you, or you’d like to think about it, since it is more of a "comfort function", but I think it might be a great addition. Let us know!

_Originally posted by @Moonbase59 in https://github.com/valentine195/obsidian-leaflet-plugin/discussions/83_

**Comment by Moonbase59** [comment]
This seems to basically work, but after updating from 3.14.1 to 3.15.0 …

- no markers are shown anymore on _both_ maps in my note (one unaltered, one modified to use `coordinates` and `zoomTag`)
- when I click "Reset view" on the map (that is correctly centered on `coordinates`), it zooms in a little more

I have this in my note and it showed 44 locations (from notes) before:

````
## Germany

```leaflet
id: Main Map
markerFolder: People
markerFolder: Locations
markerFolder: Events
#markerFolder: -Inbox
height: 500px
lat: 51.133333
long: 10.416667
minZoom: 1
maxZoom: 18
defaultZoom: 5
unit: km
distanceMultiplier: 1.3
#overlay: [green, [48.23875, 10.37595], 50 km, "Test from code block"]
#overlay: [[blue, [32, -89], 25 mi, "Jeremy Valentine?"]]
overlayTag: nearby
overlayColor: 'rgba(218, 165, 32, .6)'
```

## Near my current location

```leaflet
id: Main Map
markerFolder: People
markerFolder: Locations
markerFolder: Events
#markerFolder: +Inbox
height: 500px
lat: 48.23875
long: 10.37595
minZoom: 1
maxZoom: 18
defaultZoom: 12
unit: km
distanceMultiplier: 1.3
overlayTag: nearby
overlayColor: 'rgba(218, 165, 32, .6)'
coordinates: [[Matthias C. Hormann]]
zoomTag: nearby
```
````
![Schreiben - Obsidian v0 12 4_116](https://user-images.githubusercontent.com/3706922/121095207-2adae880-c7f0-11eb-859a-ba4ea07a03d9.png)
<small>When opening the note, all markers gone from both maps</small>

![Schreiben - Obsidian v0 12 4_117](https://user-images.githubusercontent.com/3706922/121095249-45ad5d00-c7f0-11eb-8a51-340f673d2d23.png)
<small>After clicking "Reset view", the lower map zoomed in a little</small>

Any dumb mistakes I’m making here?

**Comment by valentine195** [comment]
Any errors in the console?

I did not experience this, so curious.

**Comment by Moonbase59** [comment]
Darn, forgot to check console … one moment …

**Comment by valentine195** [comment]
In general an error should be properly bubbling to the code block now anyway.

**Comment by Moonbase59** [comment]
No warnings, no errors in console or map block. Also tried …

- modifying the `coordinates` source note, so Dataview cache sees a change
- restarting Obsidian (updated during testing from 0.12.3 to 0.12.4)
- undoing any changes I made today (2 CSS snippets)
- modifying some of the source notes for markers for Dataview to see a change

Nothing going, except auto-centering and approx. correct zooming. No markers.

**Comment by Moonbase59** [comment]
Console was still open, just got the following (Dataview update?) when switching from preview to edit mode and back:

```text
Dataview: Parsed all file prefixes (0.001s)
main.ts:148 Hotkeys for templates -> active plugins: templater-obsidian,core
index.ts:206 Dataview: Task & metadata parsing queued in 0s.
[Violation] 'requestAnimationFrame' handler took 312ms
7[Violation] Forced reflow while executing JavaScript took <N>ms
[Violation] 'requestAnimationFrame' handler took 68ms
[Violation] 'setInterval' handler took 129ms
app.js:1 [Violation] 'click' handler took 192ms
app.js:1 [Violation] 'setTimeout' handler took 58ms
cm-addons.js:6577 [Violation] 'setTimeout' handler took 158ms
app.js:1 [Violation] 'setTimeout' handler took 54ms
```

**Comment by valentine195** [comment]
Hmm... Don't think that's related. 

1.  Do ANY of the immutable marker parameters work?
2.  Are the markers created but filtered somehow?

**Comment by Moonbase59** [comment]
Testing code block:
```
marker: Check, 48.23875, 10.37595, [[Matthias C. Hormann]]
overlay: [[blue, [32, -89], 25 mi, "Someone"]]
overlay: [[green, [48.23875, 10.37595], 50 km, "Test from code block"]]
```
work.

```
#markerFolder: People
#markerFolder: Locations
#markerFolder: Events
#markerFolder: -Inbox
#markerFile: [[Matthias C. Hormann]]
#markerTags: family
markerTags: #family
```
all seem to do nothing (when uncommented).

**Comment by valentine195** [comment]
￼> Filtering, how? Not using the map’s filter anyway (it won’t show anything since no markers shown).

Yes, this is what I meant - are the markers filtered out in the filter control (sorry, on mobile 😁)

Thanks for testing the other tags. I looked through the code and I believe I see the issue. Once I have time to sit at the computer I'll work on a fix. Sorry about that!

**Comment by Moonbase59** [comment]
Well, shit happens ;-) It’s already 2:10 am here, and I should probably call it a day. You’re fast anyway, so I hope for tomorrow. (Or an easy way to go back to 3.14.1, for the time being?)

**Comment by valentine195** [comment]
If you go to the Releases tab, you can go to [release 3.14.1](https://github.com/valentine195/obsidian-leaflet-plugin/releases/tag/3.14.1) and download the `main.js` file there (should be all you need - css didn't change).

**Comment by Moonbase59** [comment]
- Markers & Overlays: All back. Phew! Thanks for the fast fix!
- zoomDelta: nifty. Works like a charm.
- Reacting on note changes: MEGA cool, markers jump immediately. (mapoverlay changes, "nearby" overlays and zoomTag changes don’t, apparently)
- map still resets to a different zoom than initially shown (from zoomTag). I think, _if_ it gets data from a zoomTag, it should use that for the reset view, else the defaultZoom from the code block.
- when filtering, mapoverlay overlays now vanish (hooray!) but those gotten from the notes’ overlayTag don’t.

**Comment by valentine195** [comment]
> - Reacting on note changes: MEGA cool, markers jump immediately. Not the center of the viewport, though (gotten from coordinates, if I change _that_ note’s location). (mapoverlay changes, "nearby" overlays and zoomTag changes don’t, apparently)

mapoverlay changes should update. They are on my end.

`overlayTag` overlays, `zoomTag` and `coordinates` would not - missed those. They will in the next update.

> I wonder if that is actually needed. On the road with a laptop driving, it would constantly move the map. The question is if that is desired or if it should stay where the user put it, viewport-wise.

`zoomTag` and `coordinates` being updated would only affect what happens when the "Reset View" button is clicked, or the map is closed and re-opened. They do not actively move the map.

> when filtering, mapoverlay overlays now vanish (hooray!) but those gotten from the notes’ overlayTag don’t ("nearby" overlay).

> "Show all markers" still shows the area where markers would be if they weren’t filtered out. I think it should only show the area for where currently visible markers are.

Will be fixed in the next update.

**Comment by Moonbase59** [comment]
Fantastic. Now for a little fun: It’s amazing how the "Current Location" note updates in the background, and the map marker automatically moves at the same time! MEGA COOL feature (and my updater script works). :+1: :100: 

![Workspace 1_118](https://user-images.githubusercontent.com/3706922/121246236-3e925780-c8a1-11eb-8384-87d95ce840cf.png)

**Comment by valentine195** [comment]
All of the above should be fixed in 3.16.1

**Comment by Moonbase59** [comment]
Oops. Tried to load 3.16.2 and failed … I’ll wait a moment.

**Comment by Moonbase59** [comment]
Ok, went through this time. Testing.

**Comment by valentine195** [comment]
Of course!

**Comment by valentine195** [comment]
Definitely not! It's come a LONG way!

**Comment by Moonbase59** [comment]
Found an "old" "bug" again with using the new `coordinates` and `overlayTag`: The "nearby" overlay isn’t size-stacked and hinders access to the smaller overlays.

Maybe you just didn’t add this to the "stacking" algorithm?

**Comment by valentine195** [comment]
Interesting. [This](https://github.com/valentine195/obsidian-leaflet-plugin/blob/1b2a35010d1fd2a5a347cf901f0e30666abb55df/src/main.ts#L242-L269) should catch all immutable overlays. I'll have to dig more into this.

**Comment by valentine195** [comment]
Ah, the stacking only runs when the map is built - not on the dynamic update.

> Also, when the "current location" note gets an update, you create a new overlay but the previous isn’t erased.

Okay, it should be - I'll take a look at it.

**Comment by Moonbase59** [comment]
Mega features introduce lots of new problems … hee hee :smile:

**Comment by Moonbase59** [comment]
I have made a little hacky Python3 script to (auto-)update a "Current Location" note, which might be valuable to the "road warriors" that _don’t_ have a GPS-enabled laptop. It updates from the machine’s current IP address and tries to get a geo location. Might be good when you’re sitting in a hotel or conference, though.

What would you think where to share it best? HERE, in the Discussions maybe, or better in the Obsidian forums?

**Comment by valentine195** [comment]
I would say Discussions as opposed to here, so it is not buried when the issue is closed. The forums is a good idea too.

**Comment by Moonbase59** [comment]
Ok so maybe the forums … actually took a while until I realized you had Discussions populated—not many do.

**Comment by Moonbase59** [comment]
So is it time for a few hours to plan in for testing today again? Just for my planning the rest of the day/night … :grin:

**Comment by valentine195** [comment]
_Mostly_, distances are not updated when the map scale unit changes - it is only converted when it needs to be displayed, and is stored internally as however it was initially defined.

**Comment by Moonbase59** [comment]
So maybe it would be a good thing to focus on an "internal unit" (like maybe Leaflet’s metres, possibly good enough, and the base unit from which the other SI units are derived for conversion), i.e.

- immediately convert into internal whenever reading something like "25 mi", "50 yd" or "100 km" from
  - the code block
  - any note
- _only_ use the internal unit for all types of calculations, like overlay stacking, distance, …
- _always_ convert from internal to desired in the presentation layer(s), like for the distance boxes, the popups, the edit boxes, …

That could alleviate the problems when users change the code block "desired display unit", _plus_ provide for exact calculations and make things easier internally. Less chance for errors and overlooking stuff, too.

**Comment by valentine195** [comment]
Probably a good idea - not going to roll this into this release, though. It would be a large change (mostly just for the overlays).

**Comment by Moonbase59** [comment]
I somehow feel it would also be a good chance for hardening and future-proofing it, though. :wink: But of course that requires some overhaul, and time. But pay off, in the long run. This plugin’s gonna _stay_!

Just let me know if and probably when you’re going to tackle that, so I can leave you alone with other nagging for a few days, hee hee. Or stay ready for testing or conferencing, of course.

**Comment by Moonbase59** [comment]
Hee hee, already secretly working on it :grin: See how it makes code leaner & cleaner?

Thanks in advance, this is getting better and better!

**Comment by Moonbase59** [comment]
Fantastic. Changing units works fine in 3.16.4, only the "current" overlay still hinders access to the smaller overlays below it.

**Comment by valentine195** [comment]
No, they're sorted before being supplied to the map. Were both of those defined from a note? If so, please let me know their locations and radiuses so I can investigate.

 I was not stacking overlays defined on the map - they will starting in 3.17.0, though.

**Comment by Moonbase59** [comment]
Thanks for your working on it! Will test 3.17.0 later the day, and come back with the data! And yes, I scrapped the CSV for now (but would still use it to import large datasets) and take _all_ values for above two maps from the "People", "Location" and "Event" notes (3 folders, with subfolders like "People/Friends & Family", "People/Business" and so on). It’s just so much more convenient.

**Comment by Moonbase59** [comment]
Testing 3.17.0 with above notes:
If I filter out "Current", I can access the overlays beneath which seem to stack okay _except_ for the 50 m "Home Zone" around my house and the problem that you almost can’t hit the 1.5 km "Turncable" overlay because the 2 km "Badeseen Münsterhausen" almost completely overlaps it.

I was thinking if maybe a "brute-force" simplistic approach could solve this: Take _all_ overlays (code block, manually created, gotten from notes) and sort them by radius. The take the largest with the lowest z-index, and so forth, the smallest getting the highest z-index.

If ever introducing _rectangle_ areas or even GeoJSON bounded areas, this will get more complicated and require a function that actually looks at the covered _areas_. I wonder if Leflet might already provide something like that, because, with maps, that’ll be a use case often encountered.

**Comment by Moonbase59** [comment]
3.17.0: Using the above "2-map-note" `-Map` only produces two gray blocks.

This `-Nearby Map` still works:

````
## Nearby

People, locations and events within `=[[-Current Location]].nearby` around location `=[[-Current Location]].location` (`=[[-Current Location]].address`).

```leaflet
id: Nearby
markerFile: [[-Current Location]]
height: 500px
minZoom: 1
maxZoom: 18
unit: km
overlayTag: nearby
overlayColor: 'rgba(218, 165, 32, .6)'
coordinates: [[-Current Location]]
zoomTag: nearby
distanceMultiplier: 1.3
geojson:
  #- [[geo-germany.json]]
  #- [[geo-bayern-minified.json]]
  - [[geo-lk-günzburg-2-geojson.json]]
  - [[geo-austria.json]]
  #- [[geo-usa-columbus.json]]
geojsonColor: 'rgba(218, 165, 32, .6)'
```
````

Can’t make out why. In the 2-map-note, tried changing ID, lat/long and other parameters but to no avail. Have still to investigate if it picks up "bad" YAML from other notes, though.

**Comment by valentine195** [comment]
Any errors in console?

**Comment by Moonbase59** [comment]
Why do I always forget the console?! (Otherwise sometimes spending hours in it …)

But anyway, I found the couse—you might want to repro:
- I have the GeoJSON files in "Locations/Anhänge" (Locations/Attachments), and location notes in "Locations", so they pull their images and stuff from their subfolder "Anhänge".
- The map uses `markerFolder: Locations` (thus also traversing the subfolders).
- The JSON files make it crap out! If I put them in another place, like the vault’s top "Anhänge", it works. As soon as I put them back, it malfunctions.

Here’s the console output. Seems you try to read YAML from _any_ type of file and destructuring multi-megabyte JSON … well … :grin: 

````
utils.ts:444 Uncaught (in promise) TypeError: Cannot destructure property 'frontmatter' of 'app.metadataCache.getFileCache(...)' as it is undefined.
    at eval (eval at <anonymous> (app.js:1), <anonymous>:22845:27)
    at Generator.next (<anonymous>)
    at fulfilled (eval at <anonymous> (app.js:1), <anonymous>:30:58)
eval @ utils.ts:444
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
fulfilled @ tslib.es6.js:73
````

**Comment by Moonbase59** [comment]
OT: Please also check feedback here: https://github.com/valentine195/obsidian-leaflet-plugin/issues/93#issuecomment-861320819

**Comment by Moonbase59** [comment]
Ignoring non '.md' files works fine now.

Only thing remaining is the stacking: https://github.com/valentine195/obsidian-leaflet-plugin/issues/84#issuecomment-861283105

**Comment by valentine195** [comment]
Hmm, the example you show [here](https://github.com/valentine195/obsidian-leaflet-plugin/issues/84#issuecomment-859771639) works correctly for me:

![image](https://user-images.githubusercontent.com/38669521/122097865-2610c880-cdde-11eb-9169-fc85956d5d9c.png)

**Comment by valentine195** [comment]
Should be fixed in 3.18.2

**Comment by Moonbase59** [comment]
Yep, seems fixed for the "nearby" overlays. The mapaoverlays from the notes are still not accessible if a "nearby" overlay is on top.

Check out the small violett-ish 5 m "dots" from the "Gewässer-Informations-Erlebnis-Pfad Münsterhausen" note!

![Knowledgebase - Obsidian v0 12 4_146](https://user-images.githubusercontent.com/3706922/122103633-2083a480-ce17-11eb-840d-89f4a61b540d.png)

**Comment by Moonbase59** [comment]
3.18.2 Further testing:
- "Current" overlay doesn’t vanish when it’s gooten from "Current" not, the only overlay & marker on the map, and I "unfilter" "Current".

**Comment by valentine195** [comment]
> EDIT 4: Can it have anything to with changing our display to the units stated in the code block (i.e., "km"? Because the small guys are only 5 m radius and display as "0 km", of course.

I don't _think_ so. This issue is kind of bizarre - they actually _are_ sorting correctly, but no matter what order I draw the overlays in, Leaflet is putting the large one at the top. Still investigating.

**Comment by Moonbase59** [comment]
As always, much appreciated!

**Comment by valentine195** [comment]
This should be fixed in 3.18.3

**Comment by valentine195** [comment]
I believe all the bugs in this issue are fixed now, right?

**Comment by Moonbase59** [comment]
I’d agree to that, let’s close it!
